[project]
name = "iabot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.13",
    "google-generativeai>=0.8.5",
    "numpy>=2.3.1",
    "python-dotenv>=1.1.1",
    "python-telegram-bot[webhooks]>=22.1",
    "scikit-learn>=1.7.0",
]
